- name: Send mail

if: failure()

uses: dawidd6/action-send-mail@v3

with:

# Required mail server address:

server_address: smtp.gmail.com

# Required mail server port:

server_port: 465

# Optional (recommended): mail server username:

username: jaivik.softweb.avnet@gmail.com

# Optional (recommended) mail server password:

password: coisxxwtytkpkdfc

# Required mail subject:

subject: Github Actions job result | Legendbrands-API-Automation

# Required recipients' addresses:

to: jaivik.brahmbhatt@softwebsolutions.com

# Required sender full name (address can be skipped):

from: Jaivik Brahmbhatt # <user@example.com>

# Optional whether this connection use TLS (default is true if server_port is 465)

secure: true

# Optional plain body:

body: Build job of ${{github.repository}} completed successfully!

# Optional HTML body read from file:

html_body: Please find attached postman API automation testing report.

# Optional unsigned/invalid certificates allowance:

ignore_cert: true

# Optional converting Markdown to HTML (set content_type to text/html too):

convert_markdown: true

# Optional attachments:

attachments: APIResults/${{env.COLLECTION_NAME_1}}.html, APIResults/${{env.COLLECTION_NAME_1}}.csv

# Optional priority: 'high', 'normal' (default) or 'low'

priority: high
